scenes:
  - name: Сцена 1
    bgColor: [0.2,0.2,0.4]
    objects:
      - name: Объект 1
        image: null
        blocks:
          - type: event
            name: start
            label: при старте
            category: event
          - type: action
            name: showCube
            label: показать куб
            category: looks
